server:
  http_listen_port: 0
  grpc_listen_port: 0
        
positions:
  filename: /tmp/positions.yaml
        
client:
  url: https://354058:<token>@logs-prod-017.grafana.net/api/prom/push
        
scrape_configs:
- job_name: <enviroment-idlocker>
  static_configs:
  - targets:
      - localhost
    labels:
      job: <enviroment-idlocker>
      __path__: /var/log/*.log
- job_name: ar-mosquitto
  static_configs:
  - targets:
      - localhost
    labels:
      job: ar-mosquitto
      __path__: /var/log/mosquitto *.log