server:
  http_listen_port: 0
  grpc_listen_port: 0
        
positions:
  filename: /tmp/positions.yaml
        
client:
  url: https://354058:glc_eyJvIjoiNzY4NDE4IiwibiI6InN0YWNrLTUwNDY5Ni1pbnRlZ3JhdGlvbi1hcnR1cml0byIsImsiOiIzY2ZNWjVoOHY0MjF2M3NaNTZxbjZQdWwiLCJtIjp7InIiOiJ1cyJ9fQ==@logs-prod-017.grafana.net/api/prom/push
        
scrape_configs:
- job_name: ar-locker
  static_configs:
  - targets:
      - localhost
    labels:
      job: ar-locker
      __path__: /var/log/*.log
- job_name: ar-mosquito
  static_configs:
  - targets:
      - localhost
    labels:
      job: ar-mosquito
      __path__: /var/log/mosquito 